### ISSUE TITLE
Please, share sample your app

### ISSUE THREAD

**Issue by tolu360** [sonnylazuardi/react-native-credit-card#1]
Hi @sonnylazuardi,

I would like to play with your library, can you please share your sample implementation (as shown in the gif on your README)? It would come highly in handy, nice work by the way.

Thanks

**Comment by sonnylazuardi** [comment]
Hi @tolu360 I'll push the example later tonight, please stay tuned 💃

**Comment by sonnylazuardi** [comment]
@tolu360 I've uploaded my example in the example project, you can try it on your device with exponent https://exp.host/@sonnylazuardi/react-native-credit-card-demos
